server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: tariff-management-system

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

tariff:
  database:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:tariff_management_system}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      min-size: ${DB_POOL_MIN_SIZE:10}
      max-size: ${DB_POOL_MAX_SIZE:50}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}
    cache:
      ttl: ${CACHE_TTL:3600}
      bom-ttl: ${BOM_CACHE_TTL:7200}

logging:
  level:
    com.tariff: INFO
    org.springframework: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method